### ISSUE TITLE
PHP Errors

### ISSUE THREAD

**Issue by formatme** [Compizfox/Backlog#1]
Notice: Undefined index: time in /var/www/dunked.asia/public/backlog/include/steamwidget.php on line 40

Warning: file_get_contents(https://api.steampowered.com/IPlayerService/GetRecentlyPlayedGames/v0001/?key=41C70922546375A9367105B1D7CA0DB2&steamid=STEAM_0:0:39690375): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error in /var/www/dunked.asia/public/backlog/include/classes.php on line 360
Column 'value' cannot be null

**Comment by Compizfox** [comment]
Thanks for submitting these bugs.

The first one (the notice) is because a certain row doesn't exist in the database on first run. It should go away after reloading the page. I will fix this in the next release.

About the second one (the error): the "500 internal server error" actually comes from Steam's servers, not yours. It is giving this error because your Steam ID is wrongly formatted. The Steam API expects it to be in STEAMID64 format, but the format in your error is 'normal' STEAMID format. I realize I should have clarified this in *config.php*'s comments (and I will certainly do so in the next release)

BTW, you can find your Steam ID in 64 format here: http://steamid.co/

**Comment by formatme** [comment]
Alright now when i try to sync hours i have this error
arning: Cannot modify header information - headers already sent by (output started at /var/www/dunked.asia/public/backlog/index.php:83) in /var/www/dunked.asia/public/backlog/pages/steam.php on line 32

**Comment by Compizfox** [comment]
Do you have output buffering disabled?

It should have been enabled by 26 of *index.php* (`ini_set('output_buffering', '1');`) but it seems like that didn't have effect.

Try creating a *.htaccess* file with the following content:

    php_flag output_buffering On

However, this will only work if you're using Apache with mod_php. For php-fpm, you probably need to enable output buffering in your php.ini. (I know it's not a pretty solution...)
